### ISSUE TITLE
Using x/X on double-quotes marks not working as expected

### ISSUE THREAD

**Issue by Epidiah** [luxbock/evil-cleverparens#113]
I'm using `evil`, `smartparens` and `evil-cleverparens`. When I invoke `evil-cp-delete-char-or-splice` via the `x` key on a single character, most of the time everything works as I expect. Parentheses, brackets, etc. are deleted along with their pair, and all other characters are deleted alone. However, double-quotes behave a bit differently. If it is the double-quote at the beginning of the string, `x` just doesn't delete anything, leaving the quotes on both sides of the string intact. If it's the quote at the end of the string, `x` deletes the ending quote, but not the beginning one. The big problem is, if these double-quotes are inside a comment it locks Emacs up and, if I don't  kill the process, it tends to use up resources until my whole computer locks up.

**Comment by tomdl89** [comment]
Thanks for the bug report @Epidiah . I can't replicate this in an `eldev emacs` session (which is the minimal environment for testing these things, with only emacs, evil, smartparens and evil-cleverparens loaded). That means it's likely caused by 1) you using a different version of these packages, or 2) your config having settings which cause this problem. Assuming you can eliminate 1), I assume your config is the relevant difference. Are you using an emacs "distribution" like doom or spacemacs? If not, then bisecting your init.el or emacs.d is quite trivial to do. Please let me know if you find anything of interest. If you use a distribution and can't easily pinpoint a cause, it may be easier to ask someone on the relevant github if they can replicate. I hope this helps us find the culprit! Cheers

**Comment by Epidiah** [comment]
Thanks for checking! I am using a distribution, [Corgi](https://github.com/corgi-emacs/corgi), which isn't frightfully huge. I think it does lock some packages down to older versions so that everyone's install of Corgi is the same. I'll have to do some read and experimenting to see how to update stuff. Otherwise, I'll start bisecting and I'll let you know where that takes me.

**Comment by tomdl89** [comment]
Feel free to re-open if you get a chance to investigate.
