### ISSUE TITLE
Would like yy to always paste on a new line

### ISSUE THREAD

**Issue by justbur** [luxbock/evil-cleverparens#14]
Here's a test case 

``` elisp
(a
 (c (d e)))
```

If I do `yy` on the second line it doesn't copy the whole line which is fine, but if I then hit `p` right away I expect the paste to be on a new line below line 2 but it's not. the result is something like this

``` elisp
(a
 (c (d e))(c (d e)))
```

I would expect something like

``` elisp
(a
 (c (d e)))
 (c (d e))
```

That's different behavior from `yyp` on 

``` elisp
(c (d e))
```

Do you agree that this is wrong?

I think it would be better to "pretend" that you yanked a whole line for pasting purposes even though you didn't

**Comment by luxbock** [comment]
Yeah you are right that the current behavior is not really in the spirit of what `yy` does in `evil`. I'm trying to think what the ideal behavior would be with respect to where the paste command gets called, and right now I'm leaning towards the following (all examples assume the parentheses ignoring behavior, location of point is indicated by `[]`):

situation:

```
(a                or    (a
 (c (d e)))[]            (c (d e))[)]
```

`yyp`:

```
(a
 (c (d e)))
[(]c (d e))
```

`yyP`:

```
[(]c (d e))
(a
 (c (d e)))
```

situation:

```
(a
 (c (d e)[)])
```

`yyp`:

```
(a
 (c (d e))
[(]c (d e)))
```

`yyP`:

```
(a
[(]c (d e))
 (c (d e)))
```

situation:

```
(a                 or      (a
 (c (d e[)]))               (c (d[ ]e)))
```

`yyp`:

```
(a
 (c (d e)
   [(]c (d e))))
```

`yyP`:

```
(a
 (c [(]c (d e))
     (d e)))
```

So the idea is that yank-line works on the most complete form found on the line, and pasting it back operates on the form the point is currently on, pasting it after (`p`) or before (`P`), inserting newlines in the right places.

The downside of this is that it might be surprising for people who would expect `yy` to act on lines rather than sexps, but I think it would be quite in spirit of the existing functionality, and quite powerful when used right.

**Comment by justbur** [comment]
Interesting idea, but I think that might be a little difficult to keep track of. I think of yyp as copying a line. I think I'd rather have your last case be a different command as in an explicit text object. I see the potential usefulness of this idea but I don't want to have to think about where the point is on the line after pasting from yyp

**Comment by luxbock** [comment]
I decided to provide an option for both styles. Should be fixed in `develop`. I've added a few more features since the last update in `master` that I will give myself a day or two of using it to see if I uncover any bugs before merging to `master` so that I don't mess up anyone who is auto-updating via MELPA.

**Comment by justbur** [comment]
Great thanks! Other than a few instances like this one, cleverparens generally does exactly what I want it to. 

I've noticed some weird stuff with strings, and I think you mentioned something like that. I'll try to describe those situations when I run into them next time.

**Comment by luxbock** [comment]
The string issues can be tracked down to `smartparens` which I use extensively, so I don't have high hopes for fixing those up anytime soon :/

**Comment by justbur** [comment]
Maybe we could get them fixed there?

**Comment by luxbock** [comment]
I believe the relevant issues are:

Fuco1/smartparens#446
Fuco1/smartparens#367

**Comment by justbur** [comment]
Just had a different thought about the original issue. Maybe this is weird, but what do you think about an explicit line text object? As in something like `yil` and `yal`? `yil` could be the line not including the end of line characters (so paste would not open up a new line). And `yal` would include them (as `yy` does by default in vim). In this case, `yal` would not yank an unbalanced expression but would add back any missing end of line stuff to behave like the vim `yyp`, corrected for parentheses. I like making the behavior you want more intentional, and I also like having both strategies always available.

**Comment by justbur** [comment]
To add to this, I think I would keep `yy` configurable as the "default" option

**Comment by luxbock** [comment]
The text-object idea is interesting, and I agree that it would be more intuitive to use at first. However I'm not sure how easy it would be to implement, as I don't know how to attach a yank-handler to a text-object. It might be possible for all I know, but I don't see a way to do it right now.

The behavior of the line-wise pasting behavior can be controlled with `evil-cleverparens-paste-lines-back-as-forms` which I've set to `t` by default. I think for the `evil-cleverparens` Spacemacs layer it would make sense to set it to `nil` for sure, but I still like keeping on by default here.

**Comment by justbur** [comment]
Makes sense to me. On the first point how does yaw work for example

**Comment by luxbock** [comment]
`evil-yank` has the following signature `(beg end type register yank-handler)`. When you call `yaw`, evil calls the `evil-a-word` text object, which returns the _range_, (check out `evil-range`) for the word under point, which `evil-yank` then uses for its `beg` and `end` and `type` arguments. The `yank-handler` is a text-property that points to a function which evil calls a pasting operation, and it can do stuff like clean up extra whitespace depending on the context in which the paste took place.

**Comment by luxbock** [comment]
After playing with this for a while I've come to the conclusion that the behavior of of pasting back lines as forms is rather confusing, so I have removed it and made your request the only default. If there was anyone actually using the way I changed it then let me know and I can put it back, but I doubt that this was the case.

**Comment by justbur** [comment]
Sounds good to me, thanks. I was starting to get used to the old default, but I think you're right that this is the better default.
