### ISSUE TITLE
Insert at beginning of sexp 

### ISSUE THREAD

**Issue by justbur** [luxbock/evil-cleverparens#26]
Hi again, I noticed that if I put the point on the first letter in a sexp and enter insert state cleverparens is adding an extra space between the point and the first letter. Is this intentional? If this doesn't happen for you I'll come up with some steps to reproduce. I'm pretty confident it happens consistently for me.

**Comment by luxbock** [comment]
It's intentional and controlled by `evil-cleverparens-use-regular-insert`.

I added this feature because I found myself having to enter the space and then go back by one character (to get auto-completion to work for example) far more often that I find myself having to delete the automatically inserted space, but I can understand that it's not for everyone. I did add a mention of the feature to the new README.

**Comment by justbur** [comment]
Ok thanks for the explanation. I should have looked at the options first
sorry. My sense is that it's one of those things that's surprising if
unexpected and is not a great default. As long as there's an option I won't
complain though.
