### ISSUE TITLE
joining forces with lispy?

### ISSUE THREAD

**Issue by drorbemet** [luxbock/evil-cleverparens#34]
I am watching editing support for lisp and Clojure quite a while now. At the moment I am using lispy hinting the author if I find something od while using it.
Using Clojure as my default language I plan to switch from my prelude based emacs to spacemacs once there is a seamless integration of lisp editing support.
The author of lispy provides the best documentation and training tutorials known to me.

Despite the potential of becoming the sweet spot in editing between text and graphical ui, I still hesitate to recommend emacs and lisp editing support because it is hard to figure out which mode and key bindings to get used to for editing text trees - lisp and even similar applications like org document trees and markdown.

I feel it as a burden having to switch key bindings for each text format although I am semantically doing the same thing - editing trees of text in multiple files.

As I see it at the moment all these projects providing support for editing text trees target a very important issue in keyboard based human computer interaction.

This seems to be a hard problem at the core and I feel respect for people tackling this one.

**Comment by luxbock** [comment]
`Lispy` is a very cool project with lots of functionality, but I think our goals are quite different. `evil-cleverparens` tries to stay faithful to the Vim keybindings while sneaking in a few of the more ambitious features behind the `Meta` key. As such I think the issue of the context switch when working in non-lisp-like languages isn't as big of a deal for us.

By piggybacking on top of `smartparens` we some help in supporting a wider variety of lisp-like languages without having to write custom code for each and every one of them, but it bears mentioning that the goal has never been for the sexp/form based commands of `evil-cleverparens` to work in non-lisp languages other than as happy accidents, as I find that a bit too daunting of a task to take on myself.

You do bring up a valid point in that it'd be nice if most of the idioms that we use to edit Lisp would work on other languages when possible, and I have configured my personal set-up to somewhat accomodate this by using [drag-stuff.el](https://github.com/rejeep/drag-stuff.el), which was the original inspiration for the expression based dragging feature of `evil-cleverparens`. Org-mode also has `org-metaup`/`org-metadown` commands which allow you to drag headlines in a similar manner.

I think finding idioms such as these and integrating them with other modes would be a worthwhile endeavor, but I think it should manifest itself not in `evil-cleverparens` but on a wider scale in configuration communities such as Spacemacs or your personal config. My advice would therefore be to come up with a list of such idioms that you come by and then lobby for Spacemacs to include those accross layers. @syl20bnr mentioned [here](https://github.com/syl20bnr/spacemacs/pull/2747) that he might consider making `evil-cleverparens` part of the Spacemacs distribution, so if that happens then I think you'd have a good case for standardising these patterns accross the layers.

**Comment by drorbemet** [comment]
... it should manifest ... on a wider scale in configuration communities ... 
Yes, that's my point. I am glad we understand each other on that issue.
And yes lobbying a list of idioms seems the way to do that because this approach is technology independent.
Hopefully the development of Spacemacs will steer in that direction and avoid distractions staying as close as possible to the underlying semantics of tree editing.

**Comment by ryepesg** [comment]
I think even if the scope of `evil-cleverparens` is only Lisp-like languages, we have a huge oportunity to offer an efficient standard layout that everybody will use in the future to efficiently manipulate tree-like structures. The only thing that is left, is integration between Lispy and `evil-cleverparens`.

Let me explain (sorry about my english, i'm not native):

1) In the future, more people will use Spacemacs:
- The best layout for editing text is Vim
- The most extensible editor is Emacs
- Evil solves the editor war
- Spacemacs is able to lower the requirements for people to access to the state of the art for text editing

2) Vim key-layout is the best for text, but it is poor for Lisp-like tree-based syntaxis
- This is the reason for the existence of smartparens, peredit, parinfer, paxedit and many more
- Lispy achieves one interface, to offer the functionality of those others, in a modal vim inspired style
- Tree-based syntaxis is not only important for Lisp, but also for simple languages like [WebAssembly](https://github.com/WebAssembly/design/blob/master/TextFormat.md): "Most of these prototypes use s-expressions because they can easily represent expression trees and ASTs"

3) But `Lispy` is not perfect
- `Lispy` has the Vim philosophy, but no the Vim key-layout
- `Lispy` is not pre-installed in the most important editor ever: Spacemacs

4) Enter `evil-cleverparens`
- Is the most carefully crafted after Vim way of working with tree-like structures
- Has the way open to be integrated in Spacemacs
- But doesn't provides all the functionality of `Lispy`... yet

5) The perfect world: `evil-cleverparens` interface to `Lispy` functionality, integrated with Spacemacs
- I already integrate `evil-cleverparens` interface with `Lispy` in Spacemacs in my own configuration. The technical aspect is easy
- But it works just for me, it is not going to be the standard layout for every new person who installs Spacemacs
- I think the only aspect left is the integration between the projects. As you already mention, the author of Spacemacs offered the posibility to include `evil-cleverparens`, so what is left is comunication between @luxbock and @abo-abo for this to happen. 

An example of my keybindings:

``` clojure
;consistency between paredit and cleverparens:
     (define-key lispy-mode-map (kbd "<") 'evil-cp-<)  
     (define-key lispy-mode-map (kbd ">") 'evil-cp->)

;before was q, changed for consistency with vimium and vimfx
     (define-key lispy-mode-map (kbd "f") 'special-lispy-ace-paren)  

;before was a, changed for consistency with f
     (define-key lispy-mode-map (kbd "F") 'special-lispy-ace-symbol)

;before was f, avoid collision, v is like down arrow, near to the oposite: b
     (define-key lispy-mode-map (kbd "v") 'special-lispy-flow)  ;

;before was w, like k but dragging (like moving windows)
     (define-key lispy-mode-map (kbd "K") 'special-lispy-move-up)

;before was s, like j but dragging (like moving windows)
     (define-key lispy-mode-map (kbd "J") 'special-lispy-move-down) 

;before was n, changed for consistency with vim
     (define-key lispy-mode-map (kbd "y") 'special-lispy-new-copy)
```

**Comment by abo-abo** [comment]
> Lispy is a very cool project with lots of functionality, but I think our goals are quite different.

The goal of lispy is to provide an efficient and well-tested interface to interacting with LISP. It looks to me that the goal of evil-cleverparens is the same.

Looking at your code, you depend on both paredit and smartparens, while making a package with the primary purpose of editing LISP code. I think it's a good idea to depend on lispy instead, since 90% of lispy are commands for navigating/editing LISP text, which you can bind to any keys that you want.  Lispy is currently better tested than paredit and smartparens; feature-wise, it's a complete superset of paredit, and while it doesn't aim to support non-LISP modes like smartparens does, it's more feature-rich for LISP modes.

**Comment by luxbock** [comment]
@abo-abo that would be such a massive re-write that it might be just easier to start over from a clean slate. I currently don't have time for such a project, but perhaps someone else will go ahead and adapt lispy to the Vim keyboard layout and we can compare results.

**Comment by abo-abo** [comment]
It's a fine idea, there was an evil-lispy effort at some point, except the author lost interest and adopted the default lispy bindings.  If there's any volunteer to do it, I'd be happy to help, but I can't do it myself since I'm only superficially familiar with vim.

**Comment by ryepesg** [comment]
Great! I would like to help with a document mapping `evil-cleverparens` keybindings to `Lispy` functionality, so other vimmers could review and arrive to an agreement.

**Comment by abo-abo** [comment]
@ryepesg If you volunteer to do it, you can start by looking at https://github.com/bcarrell/evil-lispy.  Afterwards, if you have questions like "Which command sequence should be used to get the buffer from state1 to state2?", you can ask me.

**Comment by luxbock** [comment]
I'll close this for not really being actionable.

**Comment by ryepesg** [comment]
After trying different approaches, I think the best way of integrate the projects is using Lispy themes to offer the same behavior in Lispy mode as  evil-cleverparens already does in normal mode: https://github.com/abo-abo/lispy/pull/174/files

I'm using this for a while and works as I expected.

**Comment by drorbemet** [comment]
Cool, thanks, I'll try it too.

**Comment by ryepesg** [comment]
It is not merged into Lispy yet, nor in Spacemacs. Meanwhile you can use my configuration file:
https://github.com/ryepesg/spacemacs-config/blob/master/.spacemacs

If you have problems installing lispy+cleverparens in spacemacs (as I did), you can use my layer:
https://github.com/ryepesg/spacemacs-config/tree/master/private/ricardo
