### ISSUE TITLE
Enabling evil-cleverparens complains about void symbol state

### ISSUE THREAD

**Issue by codahale** [luxbock/evil-cleverparens#47]
I just updated packages and trying to enable cleverparens displays this error:

```
Symbol's value as variable is void: state
```

This is with Spacemacs, and I currently have installed:
- evil-20160506.1021
- paredit-20160324.1215
- smartparens-20160511.812
- dash-20160510.1127

Happy to help debug further, but I’m not much of an Emacs expert.

BTW, thank you so much for this package! I work with Clojure, and this does _exactly_ what I want it do. It’s great.

**Comment by codahale** [comment]
I figured out how to get debug information for errors, and got this:

```
Debugger entered--Lisp error: (void-variable state)
  (let* ((state state) (keymap evil-cleverparens-mode-map) (key (read-kbd-macro (car it))) (def (if addp (cdr it) nil)) (bindings (list)) aux) (if state (setq aux (evil-get-auxiliary-keymap keymap state t)) (setq aux keymap)) (while key (define-key aux key def) (setq key (pop bindings) def (pop bindings))) (evil-set-keymap-prompt aux (keymap-prompt aux)))
  (progn (remove-hook (quote after-load-functions) (function evil-define-key-in-evil-cleverparens-mode-map) (quote nil)) (let* ((state state) (keymap evil-cleverparens-mode-map) (key (read-kbd-macro (car it))) (def (if addp (cdr it) nil)) (bindings (list)) aux) (if state (setq aux (evil-get-auxiliary-keymap keymap state t)) (setq aux keymap)) (while key (define-key aux key def) (setq key (pop bindings) def (pop bindings))) (evil-set-keymap-prompt aux (keymap-prompt aux))))
  (if (and (boundp (quote evil-cleverparens-mode-map)) (keymapp evil-cleverparens-mode-map)) (progn (remove-hook (quote after-load-functions) (function evil-define-key-in-evil-cleverparens-mode-map) (quote nil)) (let* ((state state) (keymap evil-cleverparens-mode-map) (key (read-kbd-macro (car it))) (def (if addp (cdr it) nil)) (bindings (list)) aux) (if state (setq aux (evil-get-auxiliary-keymap keymap state t)) (setq aux keymap)) (while key (define-key aux key def) (setq key (pop bindings) def (pop bindings))) (evil-set-keymap-prompt aux (keymap-prompt aux)))))
  (when (and (boundp (quote evil-cleverparens-mode-map)) (keymapp evil-cleverparens-mode-map)) (remove-hook (quote after-load-functions) (function evil-define-key-in-evil-cleverparens-mode-map) (quote nil)) (let* ((state state) (keymap evil-cleverparens-mode-map) (key (read-kbd-macro (car it))) (def (if addp (cdr it) nil)) (bindings (list)) aux) (if state (setq aux (evil-get-auxiliary-keymap keymap state t)) (setq aux keymap)) (while key (define-key aux key def) (setq key (pop bindings) def (pop bindings))) (evil-set-keymap-prompt aux (keymap-prompt aux))))
  evil-define-key-in-evil-cleverparens-mode-map("/Users/coda/.emacs.d/elpa/evil-cleverparens-20160511.1016/evil-cleverparens.elc")
  run-hook-with-args(evil-define-key-in-evil-cleverparens-mode-map "/Users/coda/.emacs.d/elpa/evil-cleverparens-20160511.1016/evil-cleverparens.elc")
  do-after-load-evaluation("/Users/coda/.emacs.d/elpa/evil-cleverparens-20160511.1016/evil-cleverparens.elc")
  autoload-do-load((autoload "evil-cleverparens" "Minor mode for setting up evil with smartparens and paredit\nfor an advanced modal structural editing experience.\n\n(fn &optional ARG)" t nil) evil-cleverparens-mode)
  command-execute(evil-cleverparens-mode record)
  helm-M-x(nil "evil-cleverparens-mode")
  call-interactively(helm-M-x nil nil)
  command-execute(helm-M-x)
```

**Comment by bmag** [comment]
I noticed the same, also with spacemacs. If I just include the `evil-cleverparens` layer without additional user configuration, then there's no error. But if I call `(require 'evil-cleverparens)` manually via `M-:`, then I get the same error in all kinds of operations. It's kind of hard to debug because `M-:` and `M-x` don't come up because they trigger the error.

The `(let* ((state state) (keymap evil-cleverparens-mode-map) ...` line matches part of `evil-define-key`'s source code. It seems that somehow `evil-define-key` is called with a wrong argument - the unbound variable `state` instead of an actual state (e.g. `normal`, `insert`).

I wasn't able to track the bug further, though, and going through `evil-cleverparens` code I couldn't find anything obvious.

**Comment by justbur** [comment]
It's not being called with the wrong argument. It has to do with `evil-define-key` being a macro which is getting expanded before `state` is evaluated so that `evil-define-key` is trying to save the wrong form for later execution. This kind of behavior makes it difficult to use `evil-define-key` in loops and such.

In any event this is fixed in #46.

**Comment by luxbock** [comment]
Sorry about that, I should've checked myself before merging the previous PR. I've been really busy lately so haven't had any time to look at evil-cleverparens at all. Hopefully it's fixed now.

**Comment by bmag** [comment]
works great, thank you
