### ISSUE TITLE
`C` puts cursor at beginning of next line.

### ISSUE THREAD

**Issue by sooheon** [luxbock/evil-cleverparens#5]
`evil-cp-change-line` puts cursor on the next line if:
1. It is called on or before an opening paren (sometimes)
2. It is called on or before an opening bracket
3. It is called before a closing paren or bracket

For example, calling in the following situation:

```
(defn foo [|a]
  bar)
```

Gives:

```
(defn foo []
  |bar)
```

While you almost certainly want 

```
(defn foo [|]
  bar)
```

**Comment by antonyshchenko** [comment]
For me it always puts the cursor on the next line :(

**Comment by luxbock** [comment]
This should be fixed now.

**Comment by sooheon** [comment]
Hm, unless it isn't on melpa yet (20150828.115), the bug is still there with my test case above. 

Essentially, any time there is a new line with any kind of closing delimiter, cursor is put on the next line.

**Comment by luxbock** [comment]
I just checked and the version on MELPA doesn't include the fix for this issue yet. If you want to give it a quick try you could just copy/paste the contents of `evil-cleverparens.el` into `*scratch*` and evaluate the buffer to see if it works the way you intended. At least the example you give in the issue works on my end.

**Comment by sooheon** [comment]
Can confirm works, thanks!

**Comment by antonyshchenko** [comment]
cool :+1:
